### ISSUE TITLE
Add markers for OS 4.2 and HW-W

### ISSUE THREAD

**Issue by Vogtinator** [compujuckel/ndless-apps#5]
Ndless 4.2 was released a few weeks ago and HW-W introduced a new LCD type that breaks most ndless programs and required introduction of a compatibility layer that doesn't work for some programs.

**Comment by compujuckel** [comment]
4.0 programs should be compatible with 4.2 unless they use custom syscalls, right?
Do ndless programs need to be recompiled to work on HW-W or is the new LCD orientation handled by ndless?

**Comment by Vogtinator** [comment]
> 4.0 programs should be compatible with 4.2 unless they use custom syscalls, right?

Yup.

> Do ndless programs need to be recompiled to work on HW-W or is the new LCD orientation handled by ndless?

They need to be modified and built with the current SDK to work natively, but there's also a compatibility layer that works for most programs. I'm not sure to indicate that. "Red" (Compatibility layer doesn't work), "Yellow" (works with compatibility layer) and "Green" (supports HW-W natively) maybe?

**Comment by Legimet** [comment]
And OS 4.4 now.

**Comment by compujuckel** [comment]
Done (kind of):
All programs compatible with 4.0 are now marked as compatible with 4.2 and 4.4.
Ndless versions < 4.2 are marked as deprecated.
Programs only working with deprecated Ndless versions are removed from the "Most Clicked" row.
If there are any obvious errors please tell me or use the editor on the website.
