### ISSUE TITLE
Transformer cx non cas to cas

### ISSUE THREAD

**Issue by Minjaz** [compujuckel/ndless-apps#6]
Hello, I was reading how to install ndless 4.2 in TI-planet.....and I have a question....well I have a nspire cx non cas with  serial P...B

I upgraded from to 3.0 to 4.2.0.532...but now I really need the cas version,also I already installed  ndless 4.2.

.....is there any way to transformer my  cx non cas to cx cas using that ndless??

**Comment by compujuckel** [comment]
Hi!
This bugtracker is intended for bugs/feature requests etc. relating to ndless-apps.org only.
I think it would be better to ask your question in one of the community forums like https://codewalr.us/ (english)
