### ISSUE TITLE
ndless not working

### ISSUE THREAD

**Issue by smuranjan1** [compujuckel/ndless-apps#9]
I have a TI-nspire cx running version 4.5.1.12, when i run the installer version 4.5.0, it doesnt work and shows a blank document. What do i need to do?

**Comment by compujuckel** [comment]
Hi,
this issue tracker is for problems related to the website ndless-apps.org.
For problems with Ndless itself please post in one of the community forums (e.g. https://codewalr.us/) or on the Ndless issue tracker (https://github.com/ndless-nspire/Ndless/issues).
